#pragma config(Sensor, S1,     US,             sensorEV3_Ultrasonic)
#pragma config(Sensor, S4,     CS,             sensorEV3_Color, modeEV3Color_Color)
#pragma config(Motor,  motorA,          leftWheel,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorD,          rightWheel,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*In Virtual Worlds,
left wheel - Port 'B'  and right wheel - Port 'C'.
Sonar sensor - Port '4' and Color Sensor - Port '3'.

Our bot:
left wheel - Port 'A' and right wheel  - Port 'D'.
Sonar sensor - Port '1' and Color Sensor - Port '4'*/

void colourDetect(){
	int colourVal;
	while (true){
		colourVal = getColorName(CS); // setup the sensor's name and input jack accordingly

		if(colourVal == colorGreen)
					{
						displayCenteredBigTextLine(1, "%s,%d","green", colourVal);
						//return colourVal;
					}
					else if(colourVal == colorBlue)
					{
						displayCenteredBigTextLine(1, "%s,%d","blue", colourVal);
						//return colourVal;
					}
					else
					{
						displayCenteredBigTextLine(1, "%s,%d","other", colourVal);
						//return colourVal;
					}
		}
}

task main()
{
	colourDetect();
}
