#pragma config(Sensor, S1,     US,             sensorEV3_Ultrasonic)
#pragma config(Sensor, S4,     CS,             sensorEV3_Color, modeEV3Color_Color)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void colorDetect(){
	int colourVal;
	while (true){
		colourVal = getColorName(CS); // setup the sensor's name and input jack accordingly

		if(colourVal == 3)
					{
						displayCenteredBigTextLine(1, "%s,%d","green", colourVal);
					}
					else if(colourVal == 2)
					{
						displayCenteredBigTextLine(1, "%s,%d","blue", colourVal);
					}
					else
					{
						displayCenteredBigTextLine(1, "%s,%d","other", colourVal);
					}
		}
}

task main()
{

colorDetect();

}
