#pragma config(Sensor, port2,  US,             sensorEV3_Ultrasonic)
#pragma config(Sensor, port3,  GS,             sensorVexIQ_Gyro)
#pragma config(Motor,  motor1,          leftWheel,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor4,          rightWheel,    tmotorVexIQ, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//Take the initial readings from gyro
	int degreesToTurn = 90;
	float degreesSoFar = 0;
	int	initialTurnReading = SensorValue[GS];

	//Start turning
	nSyncedMotors = synchAB;
	nSyncedTurnRatio = -100;
	motor(motor1) = -15;

	//check if we have turned enough
	while (degreesSoFar < degreesToTurn)
	{
		//update degreesSoFar
		wait1Msec(10);	// wait 10 milliseconds which is equal to .01 seconds
		int currentGyroReading = SensorValue(GS) - initialTurnReading;
		degreesSoFar = degreesSoFar + curentGyroReading*0.01;

	}

	//stop turning
	motor(motor1) = 0;

}
