#pragma config(Sensor, S1, US, sensorEV3_Ultrasonic)
#pragma config(Sensor, S4, CS, sensorEV3_Color)
#pragma config(Motor, motorA, leftWheel, tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor, motorB, armMotor, tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor, motorD, rightWheel, tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*In Virtual Worlds,
left wheel - Port 'B'  and right wheel - Port 'C'.
Sonar sensor - Port '4' and Color Sensor - Port '3'.
Our bot:
left wheel - Port 'A' and right wheel  - Port 'D'.
Sonar sensor - Port '1' and Color Sensor - Port '4'*/

/* Function List */
void resetEncoders(); // set motor encoders in wheels to 0
void twoSecBeep();	  // 2 sec beep
void stopWheels();	  // set wheel speed to 0
void lineTracking();  // move while detecting line
void moveObstacle();  // moves obstacle in green line
void turnAround();	  // turns around 180 deg for obstacle in blue line

/* main func */
task main()
{
	while (true)
	{
		// obstacle scenario
		if (getUSDistance(US) <= 10)
		{
			stopWheels(); // bot stops
			twoSecBeep(); // beeps for 2 sec

			if ((SensorValue[CS] > 7) && (SensorValue[CS] <= 10)) //green line - subject to change light intensity range
			{
				while (getUSDistance(US) >= 5)
				{
					setMotorSpeed(leftWheel, 10); // move closer towards the obstacle
					setMotorSpeed(rightWheel, 10);
				}
				stopWheels();
				moveObstacle(); // move obstacle
			}

			else if ((SensorValue[CS] > 3) && (SensorValue[CS] <= 7)) //blue line - subject to change light intensity range
			{
				turnAround(); // turn 180 deg
			}
		}

		lineTracking(); // detect line
	}
}

/* Function Def. */
// move while detecting line
void lineTracking()
{

	// color detected
	if (SensorValue[CS] <= 10)
	{
		setMotorSpeed(leftWheel, 45);
		setMotorSpeed(rightWheel, 25);
	}
	//if no color detected, turn
	else
	{
		setMotorSpeed(leftWheel, 25);
		setMotorSpeed(rightWheel, 45);
	}
}

// set motor encoders to 0
void resetEncoders()
{
	resetMotorEncoder(leftWheel);
	resetMotorEncoder(rightWheel);
}

// set wheel speed to 0
void stopWheels()
{
	motor[leftWheel] = 0;
	motor[rightWheel] = 0;
}

// 2 sec beep
void twoSecBeep()
{
	for (int i = 1; i < 3; i++)
	{
		playSoundFile("Error alarm");
		sleep(1000);
	}
}

// moves obstacle in green line
void moveObstacle()
{
	setMotorTarget(leftWheel, 113.3, 50); // bot turns right 30 deg
	waitUntilMotorStop(leftWheel);

	resetEncoders();

	while (nMotorEncoder[leftWheel] < 500)
	{
		setMotorSpeed(leftWheel, 30);
		setMotorSpeed(rightWheel, 30);
	}

	while (nMotorEncoder[leftWheel] > 0) // move back to original position
	{
		setMotorSpeed(leftWheel, -30);
		setMotorSpeed(rightWheel, -30);
	}

	stopWheels(); // stop moving

	setMotorTarget(leftWheel, -113.3, 50); // bot turns left 30 deg (back to line)
	waitUntilMotorStop(leftWheel);
}

// turns around 180 deg for obstacle in blue line
void turnAround()
{
	resetEncoders();

	while (nMotorEncoder[leftWheel] < 300) // turns counterclockwise from above
	{
		setMotorSpeed(leftWheel, -30);
		setMotorSpeed(rightWheel, 30);
	}
}
