#pragma config(Motor, motorA, leftWheel, tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor, motorD, rightWheel, tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int speed = 50;

void motorControl()
{
	// Reset the encoder to 0
	nMotorEncoder[motorA] = 0;
	nMotorEncoder[motorD] = 0;

	while (true)
	{
		motor[motorA] = speed;
		motor[motorD] = speed;
	}
}

task main()
{
	motorControl();
}
