#pragma config(Sensor, S1, CS, sensorEV3_Color)
#pragma config(Sensor, S2, US, sensorEV3_Ultrasonic)
#pragma config(Motor, motorA, mA, tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor, motorB, mB, tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor, motorC, mC, tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor, motorD, mD, tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*Global Variables*/
int speedA = 50;

/* Function List */
void stopMotors(); // stop motors
void twoSecBeep(); // Beeping for 2 sec
void stop10();	   // stop 10cm b4 obstacle
//void regline();	// REGULAR/BLACK line
//void greenline();	// GREEN line
//void blueline();	// BLUE line

/* main function */
task main()
{
	//blueline();
	stop10();
}

/* Function Definitions */
// stop motors
void stopMotors()
{
	nMotorEncoder[motorA] = 0;
	while (nMotorEncoder[motorA] <= 360)
	{
		motor[motorA] = speedA;
	}
}

// Beeping for 2 sec
void twoSecBeep()
{
	for (int i = 1; i < 3; i++)
	{
		playSoundFile("Error alarm");
		sleep(1000);
	}
}

// stop 10cm b4 obstacle
void stop10()
{
	while (true)
	{
		int dist = getUSDistance(US);
		if (dist <= 10)
		{
			twoSecBeep();
			// stop the motors
			stopMotors();
			// if line GREEN - Remove obstacle
		}
		else
		{
			continue;
		}
	}
}

// REGULAR/BLACK line
/*void regline()
{

}*/

// GREEN line
/*void greenline()
{
	//if obstacle detected, extra motor swipes it off the track -- Using motor C
	//requires 10cm scoop
	if(getUSDistance(US)<=10)
	{
		//set arm speed
		int armSpeed=30;
		nMotorEncoder[motorC]=0;
		//motorized arm turns 180 degrees to swipe the obstacle away
		while(nMotorEncoder[motorC]<=180)
		{
			motor[motorC]=armSpeed;
		}
		//motorized arm moves back into position
		while(nMotorEncoder[motorC]<=0)
		{
			motor[motorC]=-armSpeed;
		}
	}
}*/

// BLUE line
/*void blueline()
{
	//Using "one faster wheel" method from lab script. May make bot go off center once fully turned

	if(getColorName(CS)==colorBlue)
	{
		//aboutTurn variable needs to be set to the degrees the A motor needs to turn in order to complete the 180 turn. Until the bot is built, 360 is used.
		int aboutTurn= 360;
		//reset motor encoder
		nMotorEncoder[motorA]=0;
		nMotorEncoder[motorB]=0;
		//while the motor encoder reads a value less than aboutTurn
		while(nMotorEncoder[motorA]<=aboutTurn)
		{
			motor[motorA]=speedA;
			motor[motorB]=2*speedA;
		}
	}
}*/