#pragma config(Sensor, S1, CS, sensorEV3_Color)
#pragma config(Sensor, S2, US, sensorEV3_Ultrasonic)
#pragma config(Motor, motorA, mA, tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor, motorB, mB, tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor, motorC, mC, tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor, motorD, mD, tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* Function Definitions */
// stop motors
void stopMotors()
{
	nMotorEncoder[motorA] = 0;
	int speedA = 50;

	while (nMotorEncoder[motorA] <= 360)
	{
		motor[motorA] = speedA;
	}
}

// Beeping for 2 sec
void twoSecBeep()
{
	for (int i = 1; i < 3; i++)
	{
		playSoundFile("Error alarm");
		sleep(1000);
	}
}

// stop 10cm b4 obstacle
void stop10()
{
	while (true)
	{
		int dist = getUSDistance(US);
		if (dist <= 10)
		{
			twoSecBeep();
			// stop the motors
			stopMotors();
			// if line BLUE - turn 180 degrees
			break;
			// if line GREEN - Remove obstacle
		}
		else
		{
			continue;
		}
	}
}

/* main function */
task main()
{
	stop10();
}
