#pragma config(Sensor, S1,     UltraSonicEyes, sensorEV3_Ultrasonic)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#pragma config(Sensor, S2,     LightEyes,      sensorEV3_Color)

task main()
{
	// The first argument is a datalog index number.
	// The filename will be saved in the rc-data folder as
	// datalog-<INDEX>.txt
	// The format is a comma separated value file.
	// The 2nd argument is the number of columns you wish to have in the file
	// The 3rd argument specifies if you wish to append to the datalog ('right'),or if you want to overright ('flase').

	datalogFlush();
	datalogClose();
	if (!datalogOpen(20, 2, false)){
		displayCenteredTextLine(4,"Unable to open datalog");
	}
	// You can add an entry at the specified column number
	for (int i = 0;i < 100; i++)
	{
//		datalogAddShort(0, 8000 + i);
//		datalogAddLong(1, 23838 + i);
//  	datalogAddFloat(3, 678.98 / (i + 1));
	  	datalogAddFloat(0, getUSDistance(S1));
	  //	datalogAddShort(1, getColorReflected(S2));

		sleep(50); // This sleep time determines how long should the robot wait before
		// taking the next sample. It determins (affects) on the sampling rate.
		//The larger sleep time the less sampling rate!
	}
	// Make sure you close the file properly
		datalogClose();
}

//csvread
