#pragma config(Sensor, S1,     CS,             sensorEV3_Color)
#pragma config(Motor,  motorA,          leftWheel,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorD,          rightWheel,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void wheelMove(float speed)
{
	// trial-n-error the wheel speed
	setMotorSpeed(leftWheel, speed);
	setMotorSpeed(rightWheel, speed);
}

/* global var.*/
float spd = 2;

/*main func.*/
task main()
{
	// clear previous logs
	datalogFlush();
	datalogClose();
	if (!datalogOpen(5, 2, false)){
		displayCenteredTextLine(4,"Unable to open datalog");
	}

	// You can add an entry at the specified column number
	while (getMotorEncoder(rightWheel) < 250)
	{
		wheelMove(spd);

		datalogAddFloat(0, getMotorEncoder(rightWheel)); // CSV: Column 1 Data
		datalogAddShort(1, getColorReflected(CS)); // CSV: Column 2 Data

		sleep(50); // This sleep time determines how long should the robot wait before
		// taking the next sample. It determins (affects) on the sampling rate.
		//The larger sleep time the less sampling rate!
	}
	// Make sure you close the file properly
	datalogClose();
}
